<?php
include 'db.php';
$id = $_POST['num'];
$query = "SELECT * FROM ess_domain_data WHERE num = '$id'";
$result = mysqli_query($conn,$query);
$response = array();
while($row = mysqli_fetch_array($result))
{
    array_push($response, array("num"=>$row["num"], "domain_name"=>$row["domain_name"], "create_date"=>$row["create_date"], "expiry_date"=>$row['expiry_date'], "domain_registrar_name"=>$row['domain_registrar_name'], "registrant_email"=>$row['registrant_email'], "query_time"=>$row['query_time'], "registrant_city"=>$row['registrant_city'], "domain_registrar_id"=>$row['domain_registrar_id'], "domain_registrar_whois"=>$row['domain_registrar_whois'], "domain_registrar_url"=>$row['domain_registrar_url'], "registrant_name"=>$row['registrant_name'], "registrant_company"=>$row['registrant_company'], "registrant_state"=>$row['registrant_state'], "registrant_zip"=>$row['registrant_zip'], "registrant_country"=>$row['registrant_country'], "registrant_phone"=>$row['registrant_phone'], "administrative_name"=>$row['administrative_name'], "administrative_company"=>$row['administrative_company'], "administrative_address"=>$row['administrative_address'], "administrative_city"=>$row['administrative_city'], "administrative_state"=>$row['administrative_state'], "administrative_zip"=>$row['administrative_zip'], "administrative_country"=>$row['administrative_country'], "administrative_email"=>$row['administrative_email'], "administrative_phone"=>$row['administrative_phone'], "administrative_fax"=>$row['administrative_fax'], "technical_name"=>$row['technical_name'], "technical_company"=>$row['technical_company'], "technical_address"=>$row['technical_address'], "technical_city"=>$row['technical_city'], "technical_state"=>$row['technical_state'], "technical_zip"=>$row['technical_zip'], "technical_country"=>$row['technical_country'], "technical_email"=>$row['technical_email'], "technical_phone"=>$row['technical_phone'], "technical_fax"=>$row['technical_fax'], "billing_name"=>$row['billing_name'], "billing_company"=>$row['billing_company'], "billing_address"=>$row['billing_address'], "billing_city"=>$row['billing_city'], "billing_state"=>$row['billing_state'], "billing_zip"=>$row['billing_zip'], "billing_country"=>$row['billing_country'], "billing_email"=>$row['billing_email'], "billing_phone"=>$row['billing_phone'], "billing_fax"=>$row['billing_fax'], "name_server_1"=>$row['name_server_1'], "name_server_2"=>$row['name_server_2'], "name_server_3"=>$row['name_server_3'], "name_server_4"=>$row['name_server_4'], "domain_status_1"=>$row['domain_status_1'], "domain_status_2"=>$row['domain_status_2'], "domain_status_3"=>$row['domain_status_3'], "domain_status_4"=>$row['domain_status_4'], "comment"=>$row['comment']));
} 
echo json_encode($response);
mysqli_close($conn);
?>